[head]
# Use the multi-stage head as example; change hostnames or IPs to match whichever variant you started
ms-hpc-head ansible_host=172.28.10.2 ansible_user=root ansible_password=root
slim-hpc-head ansible_host=172.29.10.2 ansible_user=root ansible_password=root

[compute]
ms-hpc-compute1 ansible_host=172.28.10.3 ansible_user=root ansible_password=root
ms-hpc-compute2 ansible_host=172.28.10.4 ansible_user=root ansible_password=root
slim-hpc-compute1 ansible_host=172.29.10.3 ansible_user=root ansible_password=root
slim-hpc-compute2 ansible_host=172.29.10.4 ansible_user=root ansible_password=root

[storage]
ms-hpc-storage ansible_host=172.28.10.5 ansible_user=root ansible_password=root
slim-hpc-storage ansible_host=172.29.10.5 ansible_user=root ansible_password=root
