[supervisord]
nodaemon=true

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
stderr_logfile=/var/log/sshd.err.log
stdout_logfile=/var/log/sshd.out.log

[program:munge]
command=/usr/sbin/munged -F
autostart=true
stderr_logfile=/var/log/munge.err.log
stdout_logfile=/var/log/munge.out.log

[program:slurmd]
command=/opt/slurm/sbin/slurmd -D
autostart=true
stderr_logfile=/var/log/slurmd.err
stdout_logfile=/var/log/slurmd.out
