# Minimal slurm.conf for demo cluster
ControlMachine=head.node
SlurmUser=slurm
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmdPidFile=/var/run/slurmd.pid
SlurmdSpoolDir=/var/spool/slurmd
StateSaveLocation=/var/spool/slurmctld

AuthType=auth/munge
SchedulerType=sched/backfill
SelectType=select/cons_res
SelectTypeParameters=CR_Core_Memory

NodeName=compute[1-2] CPUs=2 RealMemory=6000 State=UNKNOWN
PartitionName=debug Nodes=compute[1-2] Default=YES MaxTime=INFINITE State=UP
