[supervisord]
nodaemon=true

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
stderr_logfile=/var/log/sshd.err.log
stdout_logfile=/var/log/sshd.out.log

[program:munge]
command=/usr/sbin/munged -F
autostart=true
stderr_logfile=/var/log/munge.err.log
stdout_logfile=/var/log/munge.out.log

[program:slurmctld]
command=/opt/slurm/sbin/slurmctld -D
autostart=true
stderr_logfile=/var/log/slurmctld.err
stdout_logfile=/var/log/slurmctld.out
