[supervisord]
nodaemon=true

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
stdout_logfile=/var/log/sshd.out
stderr_logfile=/var/log/sshd.err

[program:storage-init]
command=/usr/local/bin/storage-init.sh
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/var/log/storage.out
stderr_logfile=/var/log/storage.err
