apiVersion: v1
kind: Secret
metadata:
  name: cloud-init-compute
  namespace: hpc-cluster
stringData:
  userdata: |
    #cloud-config
    manage_etc_hosts: true
    users:
    - name: rocky
      shell: /bin/bash
      lock_passwd: false
      plain_text_passwd: Sp@rky26
    - name: root
      lock_passwd: false
      plain_text_passwd: root
    ssh_pwauth: true
    packages:
    - openssh-server
    - nfs-utils
    - python3
    - ncurses
    runcmd:
    - mkdir -p /root/.ssh /home/rocky/.ssh
    - chmod 700 /root/.ssh /home/rocky/.ssh
    - chown -R rocky:rocky /home/rocky/.ssh
    - systemctl enable sshd
    - systemctl start sshd
