apiVersion: v1
kind: Service
metadata:
  name: ssh-head
  namespace: hpc-cluster
spec:
  type: NodePort
  selector:
    kubevirt.io/vm: head
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 30222
