apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-data
  namespace: hpc-cluster
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: hpc-local
